feature(backend): add BookRepository and Book model
agory/book-store pull request #6
Opened 2018-09-04 12:52 UTC by agory

➕ Add book entity
➕ Add book repository

2018-09-04 12:54 UTC, agory commented
Qu'est ce que je peux faire comme test unitaire sur ce code ?

2018-09-04 15:01 UTC, bricebuffa requested changes

2018-09-04 15:01 UTC, bricebuffa commented on src/main/java/com/example/bookstore/entities/Book.java
> +    private String isbn;
check du côté des annotations hibernate pour les contraintes @NotEmpty, ce genre de chose

2018-09-04 15:01 UTC, bricebuffa commented on src/main/java/com/example/bookstore/entities/Book.java
> +    public void setIsbn(String isbn) {
est-ce que les accesseurs sont utiles si tu utilises un constructeur avec ton VO, sachant qu'on ne fait que de la lecture pour le moment ?

2018-09-04 19:55 UTC, bricebuffa commented on src/main/java/com/example/bookstore/entities/Book.java
> +    @NotEmpty
méa culpa je t'ais induit en erreur avec le @NotEmpty.. Tu peux utiliser le @NotNull d'HIBERNATE

2018-09-04 20:01 UTC, bricebuffa commented
pour répondre à la question faut-il des tests là-dessus pour moi c'est non, cela reviendrai à tester l'implem des répos et ça vient pas de nous.. Par contre cela correspond au point "f." les tests unitaires :-D il faudra en mettre sur la PRs de la façade ;-)

2018-09-05 07:41 UTC, agory commented on src/main/java/com/example/bookstore/entities/Book.java
> +    private String isbn;
done

2018-09-05 07:41 UTC, agory commented on src/main/java/com/example/bookstore/entities/Book.java
> +    public void setIsbn(String isbn) {
done

2018-09-05 07:42 UTC, agory commented on src/main/java/com/example/bookstore/entities/Book.java
> +    @NotEmpty
Done

2018-09-05 07:45 UTC, agory commented
Done

2018-09-05 09:13 UTC, bricebuffa approved these changes

2018-09-05 09:13 UTC, merged