feature(backend): add some book dto and facade
agory/book-store pull request #7
Opened 2018-09-04 15:05 UTC by agory

Need #6 pr

2018-09-04 19:42 UTC, bricebuffa requested changes

2018-09-04 19:42 UTC, bricebuffa commented on src/main/java/com/example/bookstore/dto/BookDetail.java
> +        this.description = book.getDescription();
place les attributs avant le constructeurs

un ordre que tu peux respecter c'est attributs static/final, attributs, constructeur vide, autres constructeur, méthodes spécifiques, getters/setters

2018-09-04 19:42 UTC, bricebuffa commented on src/main/java/com/example/bookstore/dto/BookListItem.java
> +    BookListItem(Book book) {
Le nom n'est pas clair il fait état d'une list, mais pas de liste ;-)

2018-09-04 19:42 UTC, bricebuffa commented on src/main/java/com/example/bookstore/facade/BookFacade.java
> +public class BookFacade {
La façade sera injecté comme n'importe qu'elle autre service ou composant dans spring du coup il faudra lui assigner un @Service ou @Component pour bénéficier de l'inversion de dépendance

2018-09-04 19:42 UTC, bricebuffa commented on src/main/java/com/example/bookstore/facade/BookFacade.java
> +    List<BookListItem> getBookList() {
perso je préfère ne pas utiliser le terme "get" en dehors d'un getter (qui ne contient aucune logique métier). Préférer retourner ou retrieve

2018-09-04 19:42 UTC, bricebuffa commented on src/main/java/com/example/bookstore/facade/BookFacade.java
> +        return books.stream().map(book -> new BookListItem(book));
peu être simplifier par BookListItem::new avec une lambda sur la référence de ta méthode

2018-09-04 19:42 UTC, bricebuffa commented on src/main/java/com/example/bookstore/facade/BookFacade.java
> +        return books.stream().map(book -> new BookListItem(book));
pas besoin d'un collect(toList()) à la fin de ton Stream ?

2018-09-04 20:03 UTC, bricebuffa commented
dans cette PR tu peux rajouter le point d'entrée REST... ça mange pas de pain.
En fait les points c., d., e. f. peuvent être fait dans le même commit, c'est un tout cohérent fonctionnel et tester ;-)

2018-09-05 08:19 UTC, agory commented on src/main/java/com/example/bookstore/dto/BookListItem.java
> +    BookListItem(Book book) {
Done, j'espére que le nouveau nom est correct. J'ai hésité avec BookTitleImage mais cela figé le contenu de la classe avec ses 2 propriétés.

2018-09-05 08:19 UTC, agory commented on src/main/java/com/example/bookstore/facade/BookFacade.java
> +public class BookFacade {
Done

2018-09-05 08:19 UTC, agory commented on src/main/java/com/example/bookstore/facade/BookFacade.java
> +    List<BookListItem> getBookList() {
Done

2018-09-05 08:19 UTC, agory commented on src/main/java/com/example/bookstore/facade/BookFacade.java
> +        return books.stream().map(book -> new BookListItem(book));
Done

2018-09-05 08:20 UTC, agory commented on src/main/java/com/example/bookstore/facade/BookFacade.java
> +        return books.stream().map(book -> new BookListItem(book));
Done

2018-09-05 09:15 UTC, bricebuffa commented on src/main/java/com/example/bookstore/controllers/BookController.java
> +    public List<BookShort> getAllBook(){
get cf remarque sur le nom des méthodes

2018-09-05 09:17 UTC, bricebuffa commented on src/main/java/com/example/bookstore/dto/BookDetail.java
> +public class BookDetail {
tu peux le renommer en BookDetailVO ça sera plus parlant

2018-09-05 09:18 UTC, bricebuffa commented on src/main/java/com/example/bookstore/dto/BookDetail.java
> +    public BookDetail(Book book) {
tu peux rajouter un final devant tes paramètres de méthode lorsqu'ils n'ont pas vocation à évoluer. Et si ils ont vacation à évoluer ça vaut le coup de vraiment se poser la question de pourquoi et si l'on peut faire autrement..

2018-09-05 09:24 UTC, bricebuffa commented on src/main/java/com/example/bookstore/facade/BookFacade.java
> +
Du coup tu peux rajouter les tests unitaires sur cette partie.. Utilise Mockito ;-)
/!\ Pour les prochains devs, on commencera par les tests ;-)

2018-09-05 11:27 UTC, agory commented on src/main/java/com/example/bookstore/controllers/BookController.java
> +    public List<BookShort> getAllBook(){
Ah dsl, j'ai oublié de modifier cette partie

2018-09-05 11:27 UTC, agory commented on src/main/java/com/example/bookstore/facade/BookFacade.java
> +
oki

2018-09-05 11:37 UTC, agory commented on src/main/java/com/example/bookstore/controllers/BookController.java
> +    public List<BookShort> getAllBook(){
done

2018-09-05 11:38 UTC, agory commented on src/main/java/com/example/bookstore/dto/BookDetail.java
> +public class BookDetail {
done

2018-09-05 11:38 UTC, agory commented on src/main/java/com/example/bookstore/dto/BookDetail.java
> +    public BookDetail(Book book) {
done

2018-09-05 14:25 UTC, agory commented on src/main/java/com/example/bookstore/facade/BookFacade.java
> +
Plop je viens de push un fichier de test qui ne marche pas. Je n'arrive pas trouver ce qui va pas. Peut-tu y jeter un coup d'oeil 🙏

2018-09-05 14:40 UTC, bricebuffa commented on src/main/java/com/example/bookstore/controllers/BookController.java
> +    public BookDetailVO retrieveBookByIsbn(@PathVariable(value="isbn") String isbn){
tu as peut-être une annotation ici pour exiger une chaine non nulle et non vide ;-)

2018-09-05 14:40 UTC, bricebuffa commented on src/main/java/com/example/bookstore/dto/BookDetailVO.java
> +public class BookDetailVO {
Implement Serialisable ?

2018-09-05 14:41 UTC, bricebuffa commented on src/main/java/com/example/bookstore/dto/BookShortVO.java
> +public class BookShortVO {
implement Serialisable

2018-09-05 14:41 UTC, bricebuffa commented on src/main/java/com/example/bookstore/facades/BookFacade.java
> +
ligne en trop :-D

2018-09-05 14:43 UTC, bricebuffa commented on src/main/java/com/example/bookstore/facades/BookFacade.java
> +    BookRepository bookRepository;
- doit-être autowired
- déclare tes attributs en private (le scope le plus restrictif en premier pour toujours devoir te poser la question si tu dois le faire évoluer)

2018-09-05 14:44 UTC, bricebuffa commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +    @Autowired
Pas de autowired ici le InjectMock fait le taff

2018-09-05 14:44 UTC, bricebuffa commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +    BookFacade bookFacade;
attribut déclaré en private

2018-09-05 14:45 UTC, bricebuffa commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        // when
n'hésites pas à faire des sauts de lignes entre tes sections pour airer

2018-09-05 14:45 UTC, bricebuffa commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        assertEquals(books.get(1).getTitle(),data.get(1).getTitle());
mets un espace après les virgules

2018-09-05 14:48 UTC, bricebuffa commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        Book book =new Book("C123456789012","title","authors","publisher", "Images", "Book description");
espaces après =

2018-09-05 14:50 UTC, bricebuffa commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        assertEquals(books.get(1).getTitle(),data.get(1).getTitle());
les get(1) ou get(XX) c'est moche.. Je pensais qu'on ferai ça à la prochaine itération mais on va le faire maintenant ! Ajouter AssertJ regarde comment ça marche tu auras des Matchers un peu plus sympa avec des lambdas et tout et tout pour les collections ;-)

2018-09-05 14:52 UTC, agory commented on src/main/java/com/example/bookstore/controllers/BookController.java
> +    public BookDetailVO retrieveBookByIsbn(@PathVariable(value="isbn") String isbn){
Done

2018-09-05 14:52 UTC, bricebuffa commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        List<Book> data = new ArrayList<>();
data => books (le pluriel est important et indique que tu as une collection (une List ou un Set))

2018-09-05 14:59 UTC, agory commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        List<Book> data = new ArrayList<>();
J'ai déja une variables books déclarés dans le scope du coups, je l'ai renome initialBooks

2018-09-05 15:00 UTC, agory commented on src/main/java/com/example/bookstore/controllers/BookController.java
> +    public BookDetailVO retrieveBookByIsbn(@PathVariable(value="isbn") String isbn){
done

2018-09-05 15:00 UTC, agory commented on src/main/java/com/example/bookstore/dto/BookDetailVO.java
> +public class BookDetailVO {
done

2018-09-05 15:00 UTC, agory commented on src/main/java/com/example/bookstore/dto/BookShortVO.java
> +public class BookShortVO {
done

2018-09-05 15:00 UTC, agory commented on src/main/java/com/example/bookstore/facades/BookFacade.java
> +
done

2018-09-05 15:00 UTC, agory commented on src/main/java/com/example/bookstore/facades/BookFacade.java
> +    BookRepository bookRepository;
done

2018-09-05 15:00 UTC, agory commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +    @Autowired
done

2018-09-05 15:00 UTC, agory commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +    BookFacade bookFacade;
done

2018-09-05 15:01 UTC, agory commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        // when
done

2018-09-05 15:01 UTC, agory commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        assertEquals(books.get(1).getTitle(),data.get(1).getTitle());
done

2018-09-05 15:03 UTC, agory commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        Book book =new Book("C123456789012","title","authors","publisher", "Images", "Book description");
done

2018-09-05 15:20 UTC, bricebuffa commented on src/main/java/com/example/bookstore/controllers/BookController.java
> +    BookFacade bookFacade;
private

2018-09-05 15:20 UTC, bricebuffa commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        List<Book> initaleBooks = new ArrayList<>();
inititale ?

2018-09-05 15:21 UTC, agory commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        List<Book> initaleBooks = new ArrayList<>();
je peux pas mettre books deux fois dans le même scope.

2018-09-05 15:21 UTC, bricebuffa commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        Mockito.when(bookRepository.findAll()).thenReturn(initaleBooks);
le when(...)... va dans la section Given, le // When est réservé à l'appel uniquement ;-)

2018-09-05 15:22 UTC, bricebuffa commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        assertEquals(result.getIsbn(),book.getIsbn());
espace après les virgules

2018-09-05 15:24 UTC, bricebuffa commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        List<Book> initaleBooks = new ArrayList<>();
pourquoi ne pas renommer le retour ? genre results ou booksRetrieved ?

2018-09-05 15:31 UTC, agory commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        Mockito.when(bookRepository.findAll()).thenReturn(initaleBooks);
done

2018-09-05 15:32 UTC, agory commented on src/main/java/com/example/bookstore/controllers/BookController.java
> +    BookFacade bookFacade;
done

2018-09-05 15:32 UTC, agory commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        assertEquals(result.getIsbn(),book.getIsbn());
done

2018-09-05 15:33 UTC, agory commented on src/test/java/com/example/bookstore/facades/BookFacadeTest.java
> +        List<Book> initaleBooks = new ArrayList<>();
Done

2018-09-05 15:38 UTC, agory commented
Done

2018-09-05 17:34 UTC, bricebuffa commented on pom.xml
> +			<!-- use 2.9.1 for Java 7 projects -->
comment pas nécessaire dans notre cas ;-)

2018-09-05 17:49 UTC, bricebuffa approved these changes

2018-09-05 17:49 UTC, merged